### ISSUE TITLE
How to define two items per option - for example for exec plugins

### ISSUE THREAD

**Issue by martbhell** [picotrading/ansible-collectd#1]
Hi, 

My desired output is:

<Plugin "exec">
  Exec "nobody" "/usr/local/bin/myawesomescript.sh"
</Plugin>

How would I go about defining this with your plugin and the apache2 encode macro?

<pre>
collectd_plugins_exec_db:
  - options:
    - LoadPlugin: exec
  - sections:
    - name: Plugin
      param: exec
      content:
       - options:
         - Exec: "nobody /usr/local/bin/myawesomescript.sh"
</pre>

With the critical part being

<pre>- Exec: "nobody /usr/local/bin/myawesomescript.sh"
</pre>

Setting it to the above is not enough because collectd wants quotes around the user that runs the script and the path to the script.
Setting single quotes around it all like below makes it escape all the double quotes.

<pre>
- Exec: '"nobody" "/usr/local/bin/myawesomescript.sh'"
</pre>

This is not specific to the exec plugin but also other items, like for the network plugin - how would one define a server and a port? Or for the SNMP plugin one might want to define an OID mapping.

Is there perhaps a better encoder macro or is there some magic syntax one should use for these parameters?

Thanks for a nice role :)

**Comment by jtyr** [comment]
Simply split the command into a list like this:

```
- Exec:
  - nobody
  - /usr/local/bin/myawesomescript.sh
```

There could be a problem when you are passing a number as an argument:

```
- Exec:
  - nobody
  - /usr/local/bin/myawesomescript.sh
  - 1234
```

Numbers don't have to be quoted in Collectd but in this case it probably should. You can use quote the number with an additional space and the macro will quote it as a string:

```
- Exec:
  - nobody
  - /usr/local/bin/myawesomescript.sh
  - " 1234"
```

I hope it helps. Please feel free to close this issue if you have no other questions.

**Comment by jtyr** [comment]
You might also be interested in a newer version of this role here:

https://github.com/jtyr/ansible-collectd

**Comment by martbhell** [comment]
Thanks! Writing it like that worked very nicely.
I would have filed the issue in the jtyr repo but it wasn't allowed - only pull requests.

**Comment by jtyr** [comment]
Ah. Thanks for pointing this out. I went through all the cloned repos and enabled _Issues_.
